---

####################
# Set hostname
####################

# Set hostname to internal DNS FQN. Default name is not fully qualified.
# As nodes register themselves using hostname, if not FQN other nodes will not be able to resolve it. 

- name: Add internal DNS name to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ ec2_private_dns_name }}'
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set internal DNS name as hostname
  shell: "hostname {{ ec2_private_dns_name }}"
  become: true
